# The Bluetooth of the combo chip of the Pi after its WiFi: /usr/lib/pi-bluetooth/hci-uart-after-wifi
install hci_uart /usr/lib/pi-bluetooth/hci-uart-after-wifi; /usr/sbin/modprobe --ignore-install hci_uart $CMDLINE_OPTS
