# The Bluetooth of the Pi 3 Model B, Zero W and Zero 2 W after their WiFi: /usr/lib/pi-bluetooth/hci-uart-after-wifi
install hci_uart /usr/lib/pi-bluetooth/hci-uart-after-wifi; /usr/sbin/modprobe --ignore-install hci_uart $CMDLINE_OPTS
